package dev.arcovia.mitigation.sat.dsl.tests.dummy;

import dev.arcovia.mitigation.sat.LabelCategory;
import dev.arcovia.mitigation.sat.dsl.tests.utility.CNFUtil;

/**
 * A dummy representation of incoming data for testing CNF generation.
 * <p>
 * Encapsulates the polarity, type (defaulting to "IncomingData"), and a unique value.
 */
public record DInData(boolean positive, String type, String value) {

    /**
     * Constructs a {@link DInData} instance with the given polarity, default category "IncomingData",
     * and a unique value generated by {@link CNFUtil#getNewValue()}.
     *
     * @param positive whether the data is positive
     */
    public DInData(boolean positive) {
        this(positive, LabelCategory.IncomingData.name(), String.valueOf(CNFUtil.getNewValue()));
    }
}
