package dev.arcovia.mitigation.utils.dsl.tests.dummy;

import dev.arcovia.mitigation.sat.LabelCategory;
import dev.arcovia.mitigation.utils.dsl.tests.utility.CNFUtil;

/**
 * A dummy representation of a node for testing CNF generation.
 * <p>
 * Encapsulates the polarity, type (defaulting to "Node"), and a unique value.
 */
public record DNode(boolean positive, String type, String value) {

    /**
     * Constructs a {@link DNode} instance with the given polarity, default category "Node", and a unique value generated by
     * {@link CNFUtil#getNewValue()}.
     * @param positive whether the node is positive
     */
    public DNode(boolean positive) {
        this(positive, LabelCategory.Node.name(), String.valueOf(CNFUtil.getNewValue()));
    }
}
