package dev.abunai.confidentiality.mitigation.tests;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class ModelUpscaller {

	public static void main(String[] args) {
        String input = "<flows id=\"5xh1kr\" entityName=\"Developer_Request_Account_State\" sourceNode=\"uyd5o\" destinationNode=\"1cnvoj\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#dvpfqm\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#495yo3\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"_9jRZIFi3Ee-DsdRrhZRfUQ\" entityName=\"customer_change_cc_limit\" sourceNode=\"dxnng9\" destinationNode=\"_UnKoA1i3Ee-DsdRrhZRfUQ\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#_8kjjkFi2Ee-DsdRrhZRfUQ\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#_i5uHoVi3Ee-DsdRrhZRfUQ\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"_DDuJ8Fi4Ee-DsdRrhZRfUQ\" entityName=\"change_cc_limit_csd\" sourceNode=\"_UnKoA1i3Ee-DsdRrhZRfUQ\" destinationNode=\"_e1yhglieEe-01fJ0Yo6HNg\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#_6qz-QFi3Ee-DsdRrhZRfUQ\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#_-_iYQVi2Ee-DsdRrhZRfUQ\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"kjooxa\" entityName=\"\" sourceNode=\"1cnvoj\" destinationNode=\"9zxnz\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#rab6wn\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#gv76y\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"4zxykf\" entityName=\"Customer_Banking_Data_Show_Account_State\" sourceNode=\"9zxnz\" destinationNode=\"dhglk8\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#7dlio\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#0p5bqf\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"09zks\" entityName=\"\" sourceNode=\"dhglk8\" destinationNode=\"b9ernl\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#4d824d\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#wsw6q4\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"jicost\" entityName=\"\" sourceNode=\"i0jwe\" destinationNode=\"bfppo\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#l43wk\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#fj3z0l\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"zayl1r\" entityName=\"\" sourceNode=\"sxf4g\" destinationNode=\"bfppo\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#ey45c6\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#xtg9lq\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"fmfdo\" entityName=\"Get_Loan_Offer_Process_Loan_Offer\" sourceNode=\"dxnng9\" destinationNode=\"sxf4g\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#e6jni4\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#sigr8p\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"nru6a\" entityName=\"Customer_Transfer_Money\" sourceNode=\"dxnng9\" destinationNode=\"q9xse\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#dyh2k6\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#q70tfa\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"w20by\" entityName=\"\" sourceNode=\"q9xse\" destinationNode=\"9zxnz\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#2vr30b\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#xqi29\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"_ISm0AFiUEe-5ZvwoYHO9Vg\" entityName=\"customer_show_balance\" sourceNode=\"dxnng9\" destinationNode=\"_AoaIcViUEe-5ZvwoYHO9Vg\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#_mASPwFiSEe-5ZvwoYHO9Vg\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#_XoS2gViSEe-5ZvwoYHO9Vg\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"_a7xukFiUEe-5ZvwoYHO9Vg\" entityName=\"show_balance_customer_banking_data\" sourceNode=\"_AoaIcViUEe-5ZvwoYHO9Vg\" destinationNode=\"9zxnz\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#_KasXUFiTEe-5ZvwoYHO9Vg\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#_n28PYViSEe-5ZvwoYHO9Vg\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"_kVQmcFiUEe-5ZvwoYHO9Vg\" entityName=\"customer_banking_data_balance_response\" sourceNode=\"9zxnz\" destinationNode=\"_7AoAk1iTEe-5ZvwoYHO9Vg\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#_dXHlEFiTEe-5ZvwoYHO9Vg\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#_TR8r4ViTEe-5ZvwoYHO9Vg\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"_sg-qsFiUEe-5ZvwoYHO9Vg\" entityName=\"balance_response_customer_view\" sourceNode=\"_7AoAk1iTEe-5ZvwoYHO9Vg\" destinationNode=\"_xY54YViTEe-5ZvwoYHO9Vg\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#_tK5m4FiTEe-5ZvwoYHO9Vg\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#_erGVcViTEe-5ZvwoYHO9Vg\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"_vOX5gFieEe-01fJ0Yo6HNg\" entityName=\"customer_change_settings\" sourceNode=\"dxnng9\" destinationNode=\"_cMBC41ieEe-01fJ0Yo6HNg\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#_MBc4wFieEe-01fJ0Yo6HNg\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#_8UhF0VidEe-01fJ0Yo6HNg\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"_2uYHRFieEe-01fJ0Yo6HNg\" entityName=\"change_settings_customer_settings_db\" sourceNode=\"_cMBC41ieEe-01fJ0Yo6HNg\" destinationNode=\"_e1yhglieEe-01fJ0Yo6HNg\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#_W2rV4FieEe-01fJ0Yo6HNg\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#_NjWJUVieEe-01fJ0Yo6HNg\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"_glyEMFsqEe-imMDNUFdrZA\" entityName=\"bank_clerk_get_fond_data\" sourceNode=\"_CqeuEVsqEe-imMDNUFdrZA\" destinationNode=\"_GSbFIVsqEe-imMDNUFdrZA\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#__gBZsFsoEe-imMDNUFdrZA\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#_luCCUVsoEe-imMDNUFdrZA\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"_pWOmIFsqEe-imMDNUFdrZA\" entityName=\"get_fond_data_fond_data\" sourceNode=\"_GSbFIVsqEe-imMDNUFdrZA\" destinationNode=\"_OCehElsqEe-imMDNUFdrZA\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#_cKUa8FspEe-imMDNUFdrZA\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#_BJG3YVspEe-imMDNUFdrZA\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"_2-qKsFsqEe-imMDNUFdrZA\" entityName=\"get_fond_data2_fond_data\" sourceNode=\"_JndHQVsqEe-imMDNUFdrZA\" destinationNode=\"_OCehElsqEe-imMDNUFdrZA\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#_gbII0FspEe-imMDNUFdrZA\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#_NE0bcVspEe-imMDNUFdrZA\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"_hm_3UFsvEe-imMDNUFdrZA\" entityName=\"fond_data_fond_data_response\" sourceNode=\"_OCehElsqEe-imMDNUFdrZA\" destinationNode=\"_dEqG01sqEe-imMDNUFdrZA\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#_xpvJ4FspEe-imMDNUFdrZA\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#_jF5F8VspEe-imMDNUFdrZA\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <flows id=\"_pCy6gFsvEe-imMDNUFdrZA\" entityName=\"fond_data_response_bank_clerk_view\" sourceNode=\"_dEqG01sqEe-imMDNUFdrZA\" destinationNode=\"bfppo\">\r\n"
        		+ "    <destinationPin href=\"OBM.datadictionary#_9RsEcFspEe-imMDNUFdrZA\"/>\r\n"
        		+ "    <sourcePin href=\"OBM.datadictionary#_0En38VspEe-imMDNUFdrZA\"/>\r\n"
        		+ "  </flows>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:External\" id=\"dxnng9\" entityName=\"Customer\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#__SwLIFc1Ee-aJpuBt44G8A\"/>\r\n"
        		+ "    <properties href=\"OBM.datadictionary#g10hr\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:Store\" id=\"bfppo\" entityName=\"Bank_Clerk_View\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#__SzOcFc1Ee-aJpuBt44G8A\"/>\r\n"
        		+ "    <properties href=\"OBM.datadictionary#d01uv5\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:Process\" id=\"1cnvoj\" entityName=\"request_account_state\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#__SzOdFc1Ee-aJpuBt44G8A\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:Process\" id=\"dhglk8\" entityName=\"show_account_state\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#__SzOeFc1Ee-aJpuBt44G8A\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:Store\" id=\"b9ernl\" entityName=\"Developer_View\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#__SzOfFc1Ee-aJpuBt44G8A\"/>\r\n"
        		+ "    <properties href=\"OBM.datadictionary#j62tp6\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:External\" id=\"uyd5o\" entityName=\"Developer\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#__SzOf1c1Ee-aJpuBt44G8A\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:Store\" id=\"9zxnz\" entityName=\"Customer_Banking_Data\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#__SzOglc1Ee-aJpuBt44G8A\"/>\r\n"
        		+ "    <properties href=\"OBM.datadictionary#5hnugm\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:Process\" id=\"q9xse\" entityName=\"transfer_money\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#__SzOh1c1Ee-aJpuBt44G8A\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:External\" id=\"sxf4g\" entityName=\"process_loan_offer\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#__Sz1glc1Ee-aJpuBt44G8A\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:External\" id=\"i0jwe\" entityName=\"process_loan_offer2\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#__Sz1hlc1Ee-aJpuBt44G8A\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:External\" id=\"_xY54YViTEe-5ZvwoYHO9Vg\" entityName=\"Customer_View\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#_pNCDJViTEe-5ZvwoYHO9Vg\"/>\r\n"
        		+ "    <properties href=\"OBM.datadictionary#d01uv5\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:Process\" id=\"_7AoAk1iTEe-5ZvwoYHO9Vg\" entityName=\"balance_response\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#_cCqTlViTEe-5ZvwoYHO9Vg\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:External\" id=\"_AoaIcViUEe-5ZvwoYHO9Vg\" entityName=\"show_balance\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#_j7Qc9ViSEe-5ZvwoYHO9Vg\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:Process\" id=\"_cMBC41ieEe-01fJ0Yo6HNg\" entityName=\"change_settings\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#_JryB5VieEe-01fJ0Yo6HNg\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:Store\" id=\"_e1yhglieEe-01fJ0Yo6HNg\" entityName=\"Customer_Settings_Data\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#_U5-YpVieEe-01fJ0Yo6HNg\"/>\r\n"
        		+ "    <properties href=\"OBM.datadictionary#g10hr\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:Store\" id=\"_MvXlUli3Ee-DsdRrhZRfUQ\" entityName=\"Developer_View2\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#_t9vEIVi2Ee-DsdRrhZRfUQ\"/>\r\n"
        		+ "    <properties href=\"OBM.datadictionary#j62tp6\"/>\r\n"
        		+ "    <properties href=\"OBM.datadictionary#d01uv5\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:Process\" id=\"_UnKoA1i3Ee-DsdRrhZRfUQ\" entityName=\"change_cc_limit\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#_E4r89Vi3Ee-DsdRrhZRfUQ\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:External\" id=\"_CqeuEVsqEe-imMDNUFdrZA\" entityName=\"Bank_Clerk\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#_gvS3dVsoEe-imMDNUFdrZA\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:External\" id=\"_GSbFIVsqEe-imMDNUFdrZA\" entityName=\"get_fond_data\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#_95PpJVsoEe-imMDNUFdrZA\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:External\" id=\"_JndHQVsqEe-imMDNUFdrZA\" entityName=\"get_fond_data2\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#_JNp8pVspEe-imMDNUFdrZA\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:Store\" id=\"_OCehElsqEe-imMDNUFdrZA\" entityName=\"Fond_Data\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#_ais85VspEe-imMDNUFdrZA\"/>\r\n"
        		+ "    <properties href=\"OBM.datadictionary#g10hr\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:Store\" id=\"_SYeQ8lsqEe-imMDNUFdrZA\" entityName=\"Fond_Data2\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#_sSEhpVspEe-imMDNUFdrZA\"/>\r\n"
        		+ "    <properties href=\"OBM.datadictionary#5hnugm\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:Store\" id=\"_W3GbInQSEe-hMp-vXVNX6A\" entityName=\"Bank_Clerk_View2\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#_SHR2BXQSEe-hMp-vXVNX6A\"/>\r\n"
        		+ "    <properties href=\"OBM.datadictionary#5hnugm\"/>\r\n"
        		+ "    <properties href=\"OBM.datadictionary#d01uv5\"/>\r\n"
        		+ "  </nodes>\r\n"
        		+ "  <nodes xsi:type=\"dataflowdiagram:Process\" id=\"_dEqG01sqEe-imMDNUFdrZA\" entityName=\"fond_data_response\">\r\n"
        		+ "    <behaviour href=\"OBM.datadictionary#_vNDFBVspEe-imMDNUFdrZA\"/>\r\n"
        		+ "  </nodes>";
        String regex = "("
        		+ "Store\" href|External\" href|Process\" href|target href|Assignment\" href|targetInPin href|targetFlow href|targetNode href|"
        		+ "behaviour href|destinationPin href|sourcePin href|sourceNode|destinationNode"
        		+ "|id|inputPins|outputPin|entityName)"
        		+ "=\"([^\"]*)\""; // Example regex to match all sequences of digits

        // Compile the regex
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(input);

        // Create a StringBuffer to hold the result
        StringBuffer result = new StringBuffer();

        // Replace all matches
        while (matcher.find()) {
            String match = matcher.group(); // Get the matched value
            matcher.appendReplacement(result,  match.substring(0, match.length() - 1) + "_2\""); // Append original value with "_1"
        }
        matcher.appendTail(result); // Append the remaining part of the input string

        // Output the result
        System.out.println(result.toString());
    }
	
	
}
